### ISSUE TITLE
Publish model to HuggingFace Model Hub?

### ISSUE THREAD

**Issue by setu4993** [jeongukjae/smaller-labse#1]
I [migrated the full LaBSE model](https://github.com/setu4993/convert-labse-tf-pt) from TF to PyTorch and uploaded them to the HuggingFace model hub. I saw this model on the TF hub and started migrating it for uploading to the HF Hub. I realized then that this wasn't published by Google but by @jeongukjae, so wanted to check with you before uploading it.

I have exported the model locally. I'm happy to check the changes in and upload the exported model if that's fine for you :).

**Comment by jeongukjae** [comment]
@setu4993 If you want to publish PyTorch conversion of this model to HF Hub, it is completely fine for me and it will be better if you write the this repo's link.

Thank you :)

**Comment by setu4993** [comment]
@jeongukjae: Thanks! I just [pushed the model](https://huggingface.co/setu4993/smaller-LaBSE) and noted you and this repo in there :). Thanks for your work on this!
