### ISSUE TITLE
Training time  and  Machine configuration

### ISSUE THREAD

**Issue by QzzIsCoding** [jeongukjae/smaller-labse#2]
Hi, thanks for your sharing model. I want to make a smaller model, just contains two languages(en, zh).
And I want to know the kind of machine GPU and how long does it need to  cost?

**Comment by jeongukjae** [comment]
Hi @QzzIsCoding, thanks for your attention.
I didn't trained this model. I tokenized large corpus, and picked up required vocabulary tokens for desired languages. ( And I also pruned embedding layer too :) )
This process is feasible even in my laptop.

**Comment by QzzIsCoding** [comment]
Hi, @jeongukjae, thanks for your reply.   I implemented a model(en, zh) according to your code. It is very convenient. It's a good work.
